"""Initial schema

Revision ID: 02e98369e41b
Revises: cc9475b2816a
Create Date: 2026-07-15 15:46:14.407272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e98369e41b'
down_revision: Union[str, None] = 'cc9475b2816a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('verified_username', sa.String(), nullable=True),
    sa.Column('verified_scopes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_credentials_provider'), 'connector_credentials', ['provider'], unique=True)
    op.create_table('recruiters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_username'), 'recruiters', ['username'], unique=True)
    op.create_table('search_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recruiter_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sessions_recruiter_id'), 'search_sessions', ['recruiter_id'], unique=False)
    op.create_table('search_session_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('matched_fields', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'candidate_id', name='uq_search_session_candidate'),
    sa.UniqueConstraint('session_id', 'rank', name='uq_search_session_rank')
    )
    op.create_index(op.f('ix_search_session_candidates_candidate_id'), 'search_session_candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_search_session_candidates_session_id'), 'search_session_candidates', ['session_id'], unique=False)
    op.create_index(op.f('ix_search_session_candidates_source'), 'search_session_candidates', ['source'], unique=False)
    op.create_table('sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('recruiter_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_recruiter_id'), 'sessions', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_recruiter_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_search_session_candidates_source'), table_name='search_session_candidates')
    op.drop_index(op.f('ix_search_session_candidates_session_id'), table_name='search_session_candidates')
    op.drop_index(op.f('ix_search_session_candidates_candidate_id'), table_name='search_session_candidates')
    op.drop_table('search_session_candidates')
    op.drop_index(op.f('ix_search_sessions_recruiter_id'), table_name='search_sessions')
    op.drop_table('search_sessions')
    op.drop_index(op.f('ix_recruiters_username'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_connector_credentials_provider'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    op.drop_table('candidates')
    # ### end Alembic commands ###
